//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillPipe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class EmployeeInformation
    {
        public int EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string Suffix { get; set; }
        public string Org1 { get; set; }
        public string Org1Code { get; set; }
        public string Org2 { get; set; }
        public string Org2Code { get; set; }
        public string Org3 { get; set; }
        public string Org3Code { get; set; }
        public string Org4 { get; set; }
        public string Org4Code { get; set; }
        public string WorkLocation { get; set; }
        public string WorkLocationCode { get; set; }
        public string PayGroup { get; set; }
        public string FLSAType { get; set; }
        public string JobTitle { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<System.DateTime> StatusEffectiveDate { get; set; }
        public Nullable<System.DateTime> KronosEffectiveDate { get; set; }
        public Nullable<System.DateTime> LastHireDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<int> BirthdayMonth { get; set; }
        public Nullable<int> BirthdayDay { get; set; }
        public Nullable<System.DateTime> RecordCreatedDate { get; set; }
        public Nullable<System.DateTime> AcknowledgementDate { get; set; }
        public string EepEEID { get; set; }
        public string JobCode { get; set; }
        public Nullable<int> LegalHold { get; set; }
        public string Company { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public string ADDepartment { get; set; }
        public string ManagerFirstName { get; set; }
        public string ManagerLastName { get; set; }
        public string ManagerDisplayName { get; set; }
        public Nullable<int> ManagerEmployeeNumber { get; set; }
        public string CurrentStatusCode { get; set; }
    }
}
