//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillPipe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class NameAddressMaster
    {
        public string NAM_ID { get; set; }
        public string NAME { get; set; }
        public string NAME2 { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string COUNTY { get; set; }
        public string STATE_ID { get; set; }
        public string ZIP { get; set; }
        public string TELEPHONE { get; set; }
        public string TAX_ID { get; set; }
        public string NAME_KEY { get; set; }
        public string COUNTRY_ID { get; set; }
        public string CONVERSION_DATA { get; set; }
        public string PAY_COUNTY_CODE { get; set; }
        public string FAX_NUMBER { get; set; }
        public string ADDRESS3 { get; set; }
        public string NAME_CONTROL_1099 { get; set; }
        public string NAME_1099 { get; set; }
        public string NAME2_1099 { get; set; }
        public string ADDRESS_1099 { get; set; }
        public string CITY_1099 { get; set; }
        public string STATE_1099_ID { get; set; }
        public string ZIP_1099 { get; set; }
    }
}
