//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillPipe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pipeselection
    {
        public int ID { get; set; }
        public string CC { get; set; }
        public string WN { get; set; }
        public string AFE { get; set; }
        public double OD { get; set; }
        public string WW { get; set; }
        public string GRADE { get; set; }
        public string CON { get; set; }
        public string OPT { get; set; }
        public string DRIFT { get; set; }
        public string WT { get; set; }
        public string DESC { get; set; }
        public Nullable<double> THREADLEN { get; set; }
    }
}
