//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillPipe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class SiteHeader
    {
        public string IDSITE { get; set; }
        public string SITENAME { get; set; }
        public string TYP1 { get; set; }
        public string TYP2 { get; set; }
        public string STATUS1 { get; set; }
        public string STATUS2 { get; set; }
        public Nullable<short> PROBLEMFLAG { get; set; }
        public string OPERATOR { get; set; }
        public string OPERATORCODE { get; set; }
        public string SURFACEFILENO { get; set; }
        public string SITEID1 { get; set; }
        public string SITEID2 { get; set; }
        public string SITEID3 { get; set; }
        public string CORPLEVEL1 { get; set; }
        public string CORPLEVEL2 { get; set; }
        public string CORPLEVEL3 { get; set; }
        public string CORPLEVEL4 { get; set; }
        public string COUNTRY { get; set; }
        public string STATEPROV { get; set; }
        public string COUNTY { get; set; }
        public string LEGALSURVEYPRIMARYCALC { get; set; }
        public string LEGALSURVEYPRIMARYSORT { get; set; }
        public string AREA { get; set; }
        public string FIELDNAME { get; set; }
        public string FIELDCODE { get; set; }
        public string FIELDOFFICE { get; set; }
        public string USERTXT1 { get; set; }
        public string USERTXT2 { get; set; }
        public string USERTXT3 { get; set; }
        public string USERTXT4 { get; set; }
    }
}
