//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillPipe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public System.Guid ObjectGuid { get; set; }
        public string DistinguishedName { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string Account { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string JobTitle { get; set; }
        public string Company { get; set; }
        public string ManagerDistinguishedName { get; set; }
        public string AccountType { get; set; }
        public string OrganizationalUnit { get; set; }
        public string Office { get; set; }
        public string TelephoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Street { get; set; }
        public string POBox { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
