//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillPipe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class well
    {
        public int ID { get; set; }
        public int CC { get; set; }
        public string AFE { get; set; }
        public string WN { get; set; }
    }
}
