//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillPipe.DataAccessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class WellHeader
    {
        public string IDWELL { get; set; }
        public string WELLNAME { get; set; }
        public string AREA { get; set; }
        public string BASIN { get; set; }
        public string BASINCODE { get; set; }
        public string COUNTRY { get; set; }
        public string COUNTY { get; set; }
        public string CURRENTWELLSTATUS1 { get; set; }
        public string CURRENTWELLSTATUS2 { get; set; }
        public string DIRECTIONSTOWELL { get; set; }
        public string DIVISION { get; set; }
        public string DIVISIONCODE { get; set; }
        public Nullable<System.DateTime> DTTMABANDON { get; set; }
        public Nullable<System.DateTime> DTTMFIRSTPROD { get; set; }
        public Nullable<System.DateTime> DTTMRR { get; set; }
        public Nullable<System.DateTime> DTTMSPUD { get; set; }
        public Nullable<System.DateTime> DTTMSTATUSCALC { get; set; }
        public Nullable<System.DateTime> DTTMWELLCLASS { get; set; }
        public Nullable<System.DateTime> DTTMWELLLIC { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public string OPERATOR { get; set; }
        public string OPERATORCODE { get; set; }
        public string STATEPROV { get; set; }
        public Nullable<System.DateTime> USERDTTM1 { get; set; }
        public Nullable<System.DateTime> USERDTTM2 { get; set; }
        public Nullable<System.DateTime> USERDTTM3 { get; set; }
        public Nullable<System.DateTime> USERDTTM4 { get; set; }
        public Nullable<System.DateTime> USERDTTM5 { get; set; }
        public string WELLIDA { get; set; }
        public string WELLIDB { get; set; }
        public string WELLIDC { get; set; }
        public string WELLIDD { get; set; }
        public string WELLIDE { get; set; }
        public string WELLTYP1 { get; set; }
        public string WELLTYP2 { get; set; }
    }
}
